/*
 * Build-time helper: writes Firebase config to public/firebase-config.js
 * Uses environment variables defined in Vercel (or locally)
 */
const fs = require('fs');
const path = require('path');

const out = {
  apiKey: process.env.FIREBASE_API_KEY || 'REPLACE',
  authDomain: process.env.FIREBASE_AUTH_DOMAIN || 'REPLACE',
  projectId: process.env.FIREBASE_PROJECT_ID || 'REPLACE',
  storageBucket: process.env.FIREBASE_STORAGE_BUCKET || 'REPLACE',
  messagingSenderId: process.env.FIREBASE_MESSAGING_SENDER_ID || 'REPLACE',
  appId: process.env.FIREBASE_APP_ID || 'REPLACE',
  measurementId: process.env.FIREBASE_MEASUREMENT_ID || 'REPLACE',
};

const outAppCheck = process.env.FIREBASE_APPCHECK_SITE_KEY || '';

const contents = `// Auto-generated by scripts/write-config.js; do not commit\n` +
`window.__FIREBASE_CONFIG__ = ${JSON.stringify(out, null, 2)};\n\n` +
(outAppCheck ? `window.__FIREBASE_APPCHECK_SITE_KEY__ = "${outAppCheck}";\n` : '');

fs.writeFileSync(path.join(__dirname, '../public/firebase-config.js'), contents);
console.log('wrote public/firebase-config.js');
